name = "Entropies"
uuid = "ed8fcbec-b94c-44b6-89df-898894ad9591"
repo = "https://github.com/kahaaga/Entropies.jl.git"
version = "0.1.0"

[deps]
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
