name = "ComplexityMeasures"
uuid = "ab4b797d-85ee-42ba-b621-05d793b346a2"
authors = "Kristian Agas√∏ster Haaga <kahaaga@gmail.com>, George Datseries <datseris.george@gmail.com>"
repo = "https://github.com/juliadynamics/ComplexityMeasures.jl.git"
version = "2.9.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Neighborhood = "645ca80c-8b79-4109-87ea-e1f58159d116"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StateSpaceSets = "40b095a5-5852-4c12-98c7-d43bf788e795"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
Combinatorics = "1"
DelayEmbeddings = "2.6"
Distances = "0.9, 0.10"
FFTW = "1"
Neighborhood = "0.2.4"
QuadGK = "2"
Reexport = "1"
Scratch = "1"
SpecialFunctions = "0.10, 1.0, 2"
StateSpaceSets = "1.0.4"  # contains important bugfix
StaticArrays = "0.12, 1.0"
Wavelets = "0.9"
julia = "1.5"
