name = "Entropies"
uuid = "ed8fcbec-b94c-44b6-89df-898894ad9591"
authors = "Kristian Agas√∏ster Haaga <kahaaga@gmail.com>, George Datseries <datseris.george@gmail.com>"
repo = "https://github.com/juliadynamics/Entropies.jl.git"
version = "0.11.1"

[deps]
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
DelayEmbeddings = "^1.20"
Distances = "0.9, ^0.10"
DynamicalSystems = "1.6, ^1"
NearestNeighbors = "^0.4"
Requires = "^1.1"
SpecialFunctions = "^0.10, ^1"
StaticArrays = "^0.12, ^1"
Wavelets = "^0.9"
julia = "1.5"

[extras]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Simplices = "d5428e67-3037-59ba-9ab1-57a04f0a3b6a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Conda", "DynamicalSystems", "PyCall", "Simplices", "StatsBase"]
